### ISSUE TITLE
Syntax highlighting issue, data interpreted as a branch instruction

### ISSUE THREAD

**Issue by avidrucker** [lettucegoblin/vscode-lcc#1]
Not sure if this is a bug per se, please let me know if I'm mistaken. It might be more of a feature suggestion.

For ease of reading, I'm writing my binary data in 4 bit chunks. This seems to throw off the high-lighter, though, I'm all for data to render differently than code. Perhaps data could render blue/light blue or light green if those colors are not already taken? Coincidentally, my data was interpreted by the extension as a "branch" instruction. Please see image below for compare and contrast with the matching textbook example.

![image](https://github.com/lettucegoblin/vscode-lcc/assets/6962664/f9293509-792f-49a7-b0f3-863ae3267c78)

**Comment by lettucegoblin** [comment]
Hopefully fixed pcoffset and the binary 4 chunk being interpreted as branch w/ a hacky overload. 🙌
